In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import jaccard

In [2]:
df_meta = pd.read_csv('metadata.txt', sep = '\t', usecols = ['MIT_Accession','Metagenomic_file_name'])
df_meta = df_meta.dropna()
df_meta['Metagenomic_file_name'] = df_meta['Metagenomic_file_name'].str.replace('X', '')
df_meta['Metagenomic_file_name'] = df_meta['Metagenomic_file_name'].str.replace('.', '-')
df_meta = df_meta.rename(columns={'Metagenomic_file_name': 'file'})
df_meta

   MIT_Accession                 file
0        24-0019  250728Pat_D25-10264
1        24-0020  250728Pat_D25-10265
2        24-0086  250930Pat_D25-12464
3        24-0087  250930Pat_D25-12457
4        24-0088  250930Pat_D25-12473
..           ...                  ...
85       24-0022   250513Pat_D25-7870
86       24-0023   250513Pat_D25-7871
87       24-0024   250513Pat_D25-7872
88       24-0012  250728Pat_D25-10263
89       24-0011  250728Pat_D25-10262

[72 rows x 2 columns]

In [3]:
df_mgx = pd.read_csv('nt_prok_blastn_out/nt_prok_blastn_out_taxids.txt', sep = '\t', usecols = ['file','genus'])
df_mgx = df_mgx.drop_duplicates()
df_mgx

                       file               genus
0        250513Pat_D25-7849              Rothia
1        250513Pat_D25-7849  Peptostreptococcus
3        250513Pat_D25-7849       Cutibacterium
4        250513Pat_D25-7849         Veillonella
6        250513Pat_D25-7849    Stenotrophomonas
...                     ...                 ...
318187  250930Pat_D25-12478         Phytobacter
318213  250930Pat_D25-12478         Haemophilus
318275  250930Pat_D25-12478     Ectopseudomonas
318505  250930Pat_D25-12478         Alcaligenes
318542  250930Pat_D25-12478       Stutzerimonas

[2434 rows x 2 columns]

In [5]:
df_mgx_meta = pd.merge(df_mgx,df_meta, on = 'file', how = 'left')
df_mgx_meta = df_mgx_meta.drop('file', axis=1)
df_mgx_meta['method'] = 'mgx'
df_mgx_meta

                   genus MIT_Accession method
0                 Rothia       23-1068    mgx
1     Peptostreptococcus       23-1068    mgx
2          Cutibacterium       23-1068    mgx
3            Veillonella       23-1068    mgx
4       Stenotrophomonas       23-1068    mgx
...                  ...           ...    ...
2429         Phytobacter       24-0116    mgx
2430         Haemophilus       24-0116    mgx
2431     Ectopseudomonas       24-0116    mgx
2432         Alcaligenes       24-0116    mgx
2433       Stutzerimonas       24-0116    mgx

[2434 rows x 3 columns]

In [6]:
df_meta = pd.read_csv('metadata.txt', sep = '\t', usecols = ['MIT_Accession','X16S_file_name'])
df_meta = df_meta.dropna()
df_meta['X16S_file_name'] = df_meta['X16S_file_name'].str.replace('X', '')
df_meta['X16S_file_name'] = df_meta['X16S_file_name'].str.replace('24.', '24-')
df_meta = df_meta.rename(columns={'X16S_file_name': 'file'})
df_meta

   MIT_Accession                                          file
0        24-0019  240812Pat_D24-12909_bracken_genuses.kreport2
1        24-0020  240812Pat_D24-12910_bracken_genuses.kreport2
2        24-0086  240812Pat_D24-12911_bracken_genuses.kreport2
3        24-0087  240812Pat_D24-12912_bracken_genuses.kreport2
4        24-0088  240812Pat_D24-12913_bracken_genuses.kreport2
..           ...                                           ...
83       24-0018   240222Pat_D24-2573_bracken_genuses.kreport2
84       24-0021   240222Pat_D24-2574_bracken_genuses.kreport2
85       24-0022   240222Pat_D24-2575_bracken_genuses.kreport2
86       24-0023   240222Pat_D24-2576_bracken_genuses.kreport2
87       24-0024   240222Pat_D24-2577_bracken_genuses.kreport2

[88 rows x 2 columns]

In [7]:
df_16s = pd.read_csv('16S_240222Pat_240812Pat/16s_OTU_taxids.txt', sep = '\t', usecols = ['file','genus'])
df_16s = df_16s.drop_duplicates()
df_16s

            genus                                          file
0        Toxopsis   240222Pat_D24-2554_bracken_genuses.kreport2
1      Mycoplasma   240222Pat_D24-2552_bracken_genuses.kreport2
2      Mycoplasma   240222Pat_D24-2569_bracken_genuses.kreport2
3      Mycoplasma  240812Pat_D24-12909_bracken_genuses.kreport2
4      Mycoplasma  240812Pat_D24-12910_bracken_genuses.kreport2
...           ...                                           ...
5729  Deinococcus  240812Pat_D24-12926_bracken_genuses.kreport2
5730  Deinococcus  240812Pat_D24-12928_bracken_genuses.kreport2
5731  Deinococcus  240812Pat_D24-12936_bracken_genuses.kreport2
5732     Triticum  240812Pat_D24-12928_bracken_genuses.kreport2
5733  Xylochloris  240812Pat_D24-12936_bracken_genuses.kreport2

[5734 rows x 2 columns]

In [8]:
df_16s_meta = pd.merge(df_16s,df_meta, on = 'file', how = 'left')
df_16s_meta = df_16s_meta.drop('file', axis=1)
df_16s_meta['method'] = '16s'
df_16s_meta

            genus MIT_Accession method
0        Toxopsis       23-1082    16s
1      Mycoplasma       23-1080    16s
2      Mycoplasma       24-0014    16s
3      Mycoplasma       24-0019    16s
4      Mycoplasma       24-0020    16s
...           ...           ...    ...
5729  Deinococcus       24-0101    16s
5730  Deinococcus       24-0103    16s
5731  Deinococcus       24-0113    16s
5732     Triticum       24-0103    16s
5733  Xylochloris       24-0113    16s

[5734 rows x 3 columns]

In [9]:
dfm = pd.concat([df_mgx_meta, df_16s_meta], ignore_index=True)
dfm

                   genus MIT_Accession method
0                 Rothia       23-1068    mgx
1     Peptostreptococcus       23-1068    mgx
2          Cutibacterium       23-1068    mgx
3            Veillonella       23-1068    mgx
4       Stenotrophomonas       23-1068    mgx
...                  ...           ...    ...
8163         Deinococcus       24-0101    16s
8164         Deinococcus       24-0103    16s
8165         Deinococcus       24-0113    16s
8166            Triticum       24-0103    16s
8167         Xylochloris       24-0113    16s

[8168 rows x 3 columns]

In [10]:
# Create binary table
binary_table = pd.crosstab(
    index=[dfm['MIT_Accession'], dfm['method']],
    columns=dfm['genus']
)

# Convert counts >0 to 1
binary_table = (binary_table > 0).astype(int)

# Reset index to make 'file' and 'method' normal columns
binary_table = binary_table.reset_index()

In [12]:
# Feature columns
feature_cols = binary_table.columns.difference(['genus', 'MIT_Accession', 'method'])

# MIT_Accession with both methods
valid_accessions = binary_table.groupby('MIT_Accession')['method'].nunique()
valid_accessions = valid_accessions[valid_accessions == 2].index

# Filter dataframe
df_filtered = binary_table[binary_table['MIT_Accession'].isin(valid_accessions)]

results = []

for acc in valid_accessions:
    acc_data = df_filtered[df_filtered['MIT_Accession'] == acc]
    x16s_row = acc_data[acc_data['method'] == '16s'][feature_cols].values[0]
    mgx_row = acc_data[acc_data['method'] == 'mgx'][feature_cols].values[0]

    # Skip if both rows are all zeros
    if x16s_row.sum() == 0 and mgx_row.sum() == 0:
        continue

    # Jaccard similarity
    jac_sim = 1 - jaccard(x16s_row, mgx_row)

    # Shared and unique features
    shared_features = ((x16s_row != 0) & (mgx_row != 0)).sum()
    unique_16s = ((x16s_row != 0) & (mgx_row == 0)).sum()
    unique_mgx = ((mgx_row != 0) & (x16s_row == 0)).sum()

    # Total non-zero features across both methods
    total_nonzero_features = ((x16s_row != 0) | (mgx_row != 0)).sum()
    
    # Total features in each method
    total_16s_features = (x16s_row != 0).sum()
    total_mgx_features = (mgx_row != 0).sum()

    results.append({
        'MIT_Accession': acc,
        'jaccard_similarity': jac_sim,
        'total_nonzero_features': total_nonzero_features,
        'shared_features': shared_features,
        'unique_16s': unique_16s,
        'unique_mgx': unique_mgx,
        'total_16s_features': total_16s_features,
        'total_mgx_features': total_mgx_features
    })

# Convert to DataFrame
jaccard_df = pd.DataFrame(results)

jaccard_df.to_csv('16s_vs_mgx_stats_genus.txt', sep = '\t', index=False)